[package]
name = "veltes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1"
velvet = { git = "https://github.com/raffaeleragni/velvet.git" }
#velvet = { path = "../velvet" }
uuid = { version = "1.7.0", features = ["v4"] }
# repeated transitive dependencies because of macroing requiring them at build time
serde = "1"
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
rust-embed = { version = "8.3.0", features = ["axum"] }
sqlx = { version = "0.7.4", features = ["sqlx-postgres"] }
tracing = "0.1.40"
