services:
  db:
    image: docker.io/postgres
    restart: always
    ports: ["127.0.0.1:5432:5432"]
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 1s
      timeout: 1s
      retries: 60
  migrate:
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/rust
        RUN cargo install sqlx-cli
        WORKDIR /
    volumes:
      - ./migrations:/migrations
    command: sqlx migrate run --database-url postgres://app:app@db/app
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    ports: ["127.0.0.1:8888:8080"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
  mail:
    image: docker.io/rnwood/smtp4dev:v3
    ports: ["2525:25", "8989:80"]
    environment:
      - ServerOptions__TlsMode=ImplicitTls
      - ServerOptions__Login=user
      - ServerOptions__Password=password
